services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - imagelitenetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - imagelitenetwork

  sbootapp:
#    build:
#      dockerfile: Dockerfile
#      context: ./imageliteapi
    image: renatoguii/imageliteproject:sbootapp # Usando imagem do Docker Hub
    container_name: imageliteapi
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - imagelitenetwork
    environment:
      - "POSTGRES_HOST=db"

  appweb:
#    build:
#      dockerfile: Dockerfile
#      context: ./imagelite
    image: renatoguii/imageliteproject:appweb  # Usando a imagem do Docker Hub
    container_name: imageliteapp
    depends_on:
      - sbootapp
    ports:
      - "3000:3000"
    networks:
      - imagelitenetwork
    expose:
      - 3000

networks:
  imagelitenetwork:
    driver: bridge