# Config Local
# Configuração do Banco de Dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelite
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  # Configuração de upload de arquivos
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# Production
--- # o que vier após esses 3 traços, será sobrescrito
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/imagelite
